#!/bin/bash
LOCK_OPT="-e -i /home/$USER/background.png -c 002b36"

revert() {
    xset dpms 0 0 0
}

lock() {
    trap revert SIGHUP SIGINT SIGTERM
    xset +dpms dpms 5 5 5
    i3lock -n ${LOCK_OPT}
    revert
}

case "$1" in
    lock)
	lock
	;;
    logout)
	i3-msg exit
	;;
    suspend)
	i3lock ${LOCK_OPT} && systemctl suspend
	;;
    hibernate)
	i3lock ${LOCK_OPT} && systemctl hibernate
	;;
    reboot)
	systemctl reboot
	;;
    shutdown)
	systemctl poweroff
	;;
    *)
	echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
	exit 2
esac

exit 0
